import express from 'express';
import path from 'path';
import 'dotenv/config';
import cors from 'cors';
import { fileURLToPath } from 'url';
import cookieParser from 'cookie-parser';

import authRoutes from './routes/auth.route.js';
import productRoutes from './routes/product.route.js';
import cartRoutes from './routes/cart.route.js';
import couponRoutes from './routes/coupon.route.js';
import paymentRoutes from './routes/payment.route.js';
import analyticsRoutes from './routes/analytics.route.js';

import { connectDB } from './lib/db.js';

const app = express();
const PORT = process.env.PORT || 5000;
// Needed to have ESM recognize __dirname
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Accept requests from frontend server
app.use(
  cors({
    origin: process.env.CLIENT_DOMAIN,
  })
);

// Serve static files from the dist folder generated by Vite
app.use(express.static(path.join(__dirname, '../client/dist')));
// Parse data client sends as JSON with Content-Type: application/json
app.use(express.json({ limit: '10mb' }));
// Parse data client sends in HTML forms with Content-Type: application/x-www-form-urlencoded
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());

// Authentication
app.use('/api/auth', authRoutes);

// Handling Products
app.use('/api/products', productRoutes);

// Handling Checkout Cart
app.use('/api/cart', cartRoutes);

// Handling Coupons
app.use('/api/coupons', couponRoutes);

// Handling Payment
app.use('/api/payment', paymentRoutes);

// Analytics Dashboard
app.use('/api/analytics', analyticsRoutes);

// Serve entry file to app
app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, '../client/dist/index.html'));
});

// Global error handler
app.use((err, req, res, next) => {
  res.status(err.status || 500);
  return res.send(`Global error handler: ${err.message}`);
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
  // Connect to database
  connectDB();
});
